# Generated by Django 6.1.2 on 2026-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
