# Generated by Django 6.1.2 on 2026-10-08 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cash_refund', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Naqd qaytarilgan')),
                ('debt_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Qarzdan ayrilgan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn')),
            ],
        ),
    ]
