# Generated by Django 6.1.2 on 2026-10-08 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salereturn_salereturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Asl narx'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name="Boshlang'ich naqd")),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Kutilgan naqd')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Haqiqiy naqd')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.shift'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.shift'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.shift'),
        ),
    ]
